# docker config version
version: "3.1"
# begin listing containers
services:
  # container
  frontend:
    # image to be used for spin-up
    build: frontend
    # container name to be used for reference
    # container_name: frontend
    # docker's volumes area, takes code from ./client and puts it in /app in the docker container
    # local filepath : container file path
    # volumes:
    #   - "./frontend:/app"
    # port connection
    # local port : container port
    ports:
      - "3000:3000"
    # internal network for communication between containers
    networks:
      - wish-network
    # will not spin-up this container until the dependencies have spun-up
    depends_on:
      - backend

  db:
    image: postgres
  #   container_name: db
    ports:
      - "5432:5432"
    environment:
      # specific to postgresql for spinning-up the database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
  #   # data storage
  #   # host path : container path
  #   volumes:
  #     - ./my_data_directory:/var/lib/postgresql/data
    networks:
      - wish-network

  backend:
    build: backend
    # container_name: server
    # volumes:
    #   - "./backend:/app"
    ports:
      - "3001:3000"
    networks:
      - wish-network
    environment:
      # specific to postgresql for connecting to the database
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/db
    depends_on:
      - db



# set-up network for container communication
networks:
  wish-network:
    driver: bridge